from pathlib import Path

DEFAULT_OUTPUT_DIR = Path('analysedaten') / 'output'
REPORTS_DIRNAME = 'reports'
PREDICTION_DIRNAME = 'prediction'
PLOTS_DIRNAME = 'plots'

PHASE_SPEED_THRESHOLD = 5.0
MIN_STATE_SECONDS = 30
DEFAULT_STARTUP_SECONDS = 60

QUALITY_THRESHOLDS = {
    1: 2.5,
    2: 2.5,
    3: 1.5,
}
DEFAULT_QUALITY_THRESHOLD = 2.0
QUALITY_SHARE_ABS_GT_2PCT_THRESHOLD = 4.5
QUALITY_SHARE_BAD_THRESHOLD = 5.0
QUALITY_LOCAL_WINDOW_SECONDS = 30
QUALITY_LOCAL_MIN_WINDOW_SAMPLES = 6
QUALITY_LOCAL_PEAK_SIGMA_THRESHOLD = 4.95
QUALITY_LOCAL_PEAK_SHARE_ABS_GT_2PCT_THRESHOLD = 60.0
QUALITY_LOCAL_EDGE_CENTER_SHIFT_THRESHOLD = 1.5
QUALITY_MIN_EVIDENCE_FOR_BAD = 2

RANDOM_FOREST_DEFAULTS = {
    'n_estimators': 300,
    'max_depth': 6,
    'min_samples_leaf': 2,
    'random_state': 42,
    'class_weight': 'balanced',
    'n_jobs': 1,
}
